---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm install -g npm@6
  - npm --version
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
